/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface WvSitemapArea {
    'sitemap': Object;
  }
  interface WvSitemapAreaAttributes extends StencilHTMLAttributes {
    'sitemap'?: Object;
  }

  interface WvSitemapCard {
    'area': Object;
  }
  interface WvSitemapCardAttributes extends StencilHTMLAttributes {
    'area'?: Object;
    'onSetActiveArea'?: (event: CustomEvent) => void;
  }

  interface WvSitemapExplorer {
    'hide': () => void;
    'show': () => void;
    'sitemap': string;
  }
  interface WvSitemapExplorerAttributes extends StencilHTMLAttributes {
    'sitemap'?: string;
  }

  interface WvSitemapNode {
    'node': Object;
  }
  interface WvSitemapNodeAttributes extends StencilHTMLAttributes {
    'node'?: Object;
  }

  interface WvSitemapSubarea {
    'area': Object;
    'areasCount': Number;
  }
  interface WvSitemapSubareaAttributes extends StencilHTMLAttributes {
    'area'?: Object;
    'areasCount'?: Number;
    'onRemoveActiveArea'?: (event: CustomEvent) => void;
    'onShowNextArea'?: (event: CustomEvent) => void;
    'onShowPrevArea'?: (event: CustomEvent) => void;
  }
}

declare global {
  interface StencilElementInterfaces {
    'WvSitemapArea': Components.WvSitemapArea;
    'WvSitemapCard': Components.WvSitemapCard;
    'WvSitemapExplorer': Components.WvSitemapExplorer;
    'WvSitemapNode': Components.WvSitemapNode;
    'WvSitemapSubarea': Components.WvSitemapSubarea;
  }

  interface StencilIntrinsicElements {
    'wv-sitemap-area': Components.WvSitemapAreaAttributes;
    'wv-sitemap-card': Components.WvSitemapCardAttributes;
    'wv-sitemap-explorer': Components.WvSitemapExplorerAttributes;
    'wv-sitemap-node': Components.WvSitemapNodeAttributes;
    'wv-sitemap-subarea': Components.WvSitemapSubareaAttributes;
  }


  interface HTMLWvSitemapAreaElement extends Components.WvSitemapArea, HTMLStencilElement {}
  var HTMLWvSitemapAreaElement: {
    prototype: HTMLWvSitemapAreaElement;
    new (): HTMLWvSitemapAreaElement;
  };

  interface HTMLWvSitemapCardElement extends Components.WvSitemapCard, HTMLStencilElement {}
  var HTMLWvSitemapCardElement: {
    prototype: HTMLWvSitemapCardElement;
    new (): HTMLWvSitemapCardElement;
  };

  interface HTMLWvSitemapExplorerElement extends Components.WvSitemapExplorer, HTMLStencilElement {}
  var HTMLWvSitemapExplorerElement: {
    prototype: HTMLWvSitemapExplorerElement;
    new (): HTMLWvSitemapExplorerElement;
  };

  interface HTMLWvSitemapNodeElement extends Components.WvSitemapNode, HTMLStencilElement {}
  var HTMLWvSitemapNodeElement: {
    prototype: HTMLWvSitemapNodeElement;
    new (): HTMLWvSitemapNodeElement;
  };

  interface HTMLWvSitemapSubareaElement extends Components.WvSitemapSubarea, HTMLStencilElement {}
  var HTMLWvSitemapSubareaElement: {
    prototype: HTMLWvSitemapSubareaElement;
    new (): HTMLWvSitemapSubareaElement;
  };

  interface HTMLElementTagNameMap {
    'wv-sitemap-area': HTMLWvSitemapAreaElement
    'wv-sitemap-card': HTMLWvSitemapCardElement
    'wv-sitemap-explorer': HTMLWvSitemapExplorerElement
    'wv-sitemap-node': HTMLWvSitemapNodeElement
    'wv-sitemap-subarea': HTMLWvSitemapSubareaElement
  }

  interface ElementTagNameMap {
    'wv-sitemap-area': HTMLWvSitemapAreaElement;
    'wv-sitemap-card': HTMLWvSitemapCardElement;
    'wv-sitemap-explorer': HTMLWvSitemapExplorerElement;
    'wv-sitemap-node': HTMLWvSitemapNodeElement;
    'wv-sitemap-subarea': HTMLWvSitemapSubareaElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
