/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface WvDatasourceManage {
    'apiRootUrl': string;
    'datasourceId': string;
    'pageDatasourceId': string;
    'pageDatasourceName': string;
    'pageDatasourceParams': string;
    'show': boolean;
  }
  interface WvDatasourceParamForm {}
  interface WvDatasourceStep1 {}
  interface WvDatasourceStep2 {}
}

declare global {


  interface HTMLWvDatasourceManageElement extends Components.WvDatasourceManage, HTMLStencilElement {}
  var HTMLWvDatasourceManageElement: {
    prototype: HTMLWvDatasourceManageElement;
    new (): HTMLWvDatasourceManageElement;
  };

  interface HTMLWvDatasourceParamFormElement extends Components.WvDatasourceParamForm, HTMLStencilElement {}
  var HTMLWvDatasourceParamFormElement: {
    prototype: HTMLWvDatasourceParamFormElement;
    new (): HTMLWvDatasourceParamFormElement;
  };

  interface HTMLWvDatasourceStep1Element extends Components.WvDatasourceStep1, HTMLStencilElement {}
  var HTMLWvDatasourceStep1Element: {
    prototype: HTMLWvDatasourceStep1Element;
    new (): HTMLWvDatasourceStep1Element;
  };

  interface HTMLWvDatasourceStep2Element extends Components.WvDatasourceStep2, HTMLStencilElement {}
  var HTMLWvDatasourceStep2Element: {
    prototype: HTMLWvDatasourceStep2Element;
    new (): HTMLWvDatasourceStep2Element;
  };
  interface HTMLElementTagNameMap {
    'wv-datasource-manage': HTMLWvDatasourceManageElement;
    'wv-datasource-param-form': HTMLWvDatasourceParamFormElement;
    'wv-datasource-step1': HTMLWvDatasourceStep1Element;
    'wv-datasource-step2': HTMLWvDatasourceStep2Element;
  }
}

declare namespace LocalJSX {
  interface WvDatasourceManage extends JSXBase.HTMLAttributes<HTMLWvDatasourceManageElement> {
    'apiRootUrl'?: string;
    'datasourceId'?: string;
    'pageDatasourceId'?: string;
    'pageDatasourceName'?: string;
    'pageDatasourceParams'?: string;
    'show'?: boolean;
  }
  interface WvDatasourceParamForm extends JSXBase.HTMLAttributes<HTMLWvDatasourceParamFormElement> {}
  interface WvDatasourceStep1 extends JSXBase.HTMLAttributes<HTMLWvDatasourceStep1Element> {}
  interface WvDatasourceStep2 extends JSXBase.HTMLAttributes<HTMLWvDatasourceStep2Element> {}

  interface IntrinsicElements {
    'wv-datasource-manage': WvDatasourceManage;
    'wv-datasource-param-form': WvDatasourceParamForm;
    'wv-datasource-step1': WvDatasourceStep1;
    'wv-datasource-step2': WvDatasourceStep2;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


