/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface WvNps {
    'class': string;
    'name': string;
    'rating': number;
  }
}

declare global {


  interface HTMLWvNpsElement extends Components.WvNps, HTMLStencilElement {}
  var HTMLWvNpsElement: {
    prototype: HTMLWvNpsElement;
    new (): HTMLWvNpsElement;
  };
  interface HTMLElementTagNameMap {
    'wv-nps': HTMLWvNpsElement;
  }
}

declare namespace LocalJSX {
  interface WvNps extends JSXBase.HTMLAttributes<HTMLWvNpsElement> {
    'class'?: string;
    'name'?: string;
    'rating'?: number;
  }

  interface IntrinsicElements {
    'wv-nps': WvNps;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


