/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface StarRating {
    'hoverClass': string;
    'maxValue': number;
    'name': string;
    'offClass': string;
    'onClass': string;
    'rating': number;
    'titleCsv': string;
  }
}

declare global {


  interface HTMLStarRatingElement extends Components.StarRating, HTMLStencilElement {}
  var HTMLStarRatingElement: {
    prototype: HTMLStarRatingElement;
    new (): HTMLStarRatingElement;
  };
  interface HTMLElementTagNameMap {
    'star-rating': HTMLStarRatingElement;
  }
}

declare namespace LocalJSX {
  interface StarRating extends JSXBase.HTMLAttributes<HTMLStarRatingElement> {
    'hoverClass'?: string;
    'maxValue'?: number;
    'name'?: string;
    'offClass'?: string;
    'onClass'?: string;
    'rating'?: number;
    'titleCsv'?: string;
  }

  interface IntrinsicElements {
    'star-rating': StarRating;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


